# Generated by Django 5.0.4 on 2024-10-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocalculation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.CharField(max_length=100),
        ),
    ]
