# Generated by Django 5.0.4 on 2024-10-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocalculation_app', '0002_alter_user_aadhar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_user',
            field=models.BooleanField(default=False, verbose_name='academic user'),
        ),
        migrations.AddField(
            model_name='user',
            name='govt_idcard',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='user',
            name='govt_user',
            field=models.BooleanField(default=False, verbose_name='govt user'),
        ),
        migrations.AddField(
            model_name='user',
            name='institute_idcard',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='private_user',
            field=models.BooleanField(default=False, verbose_name='private user'),
        ),
    ]
