# Generated by Django 5.0.4 on 2024-11-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocalculation_app', '0003_user_academic_user_user_govt_idcard_user_govt_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goverment_idcard_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_idcard_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
