# Generated by Django 5.0.4 on 2024-11-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocalculation_app', '0005_user_user_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Panding', max_length=100),
        ),
    ]
