# Generated by Django 5.0.4 on 2024-11-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocalculation_app', '0006_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
